### ISSUE TITLE
MainStoryboard

### ISSUE THREAD

**Issue by milenaalcantara** [BeatrizLdS/Stopoint#24]
https://github.com/BeatrizLdS/Stopoint/blob/bcb9e9970cee527bfb457bfe2d897e8d1e054730/Stopoint/Base.lproj/Main.storyboard#L1-L24

Oi Bea ❤️

Estava olhando seu código e percebi que você não está usando storyboard. Em vista disso seria interessante deletar o arquivo main storyboard. Deixar o link de um dos CBLs de uma equipe minha para te ajudar no processo 😁
[MLP - FigJam](https://www.figma.com/file/uM9A2RP3gATOk4mxIMotSE/MLP?node-id=0%3A1)

Qualquer coisa, chama -> 🔥

**Comment by BeatrizLdS** [comment]
Não tô conseguindo acessar o teu figJam que tu enviou ;-;
