### ISSUE TITLE
Retorno nil em caso de voos indisponíveis

### ISSUE THREAD

**Issue by lvasantos** [BeatrizLdS/Stopoint#33]
Na simulação do caso abaixo também ocorre de o aplicativo apresentar uma tela em branco, sem informar ao usuário se está carregando ou se ocorreu um erro. O erro vem de a API não encontrar um trajeto que aceite as especificações digitadas. Uma boa ideia seria um símbolo de loading e tratar esse caso nil para informar ao usuário por meio de um alerta ou algo similar que ocorreu um erro.

- [x] Tratar o erro nil
- [x] Mostrar alerta em caso de não ter voos disponíveis

<p align="center">
<img width="185" alt="Pesquisar" src="https://user-images.githubusercontent.com/82406248/199001279-cf2e6e41-ae10-4415-b1cf-ee5564bedd4d.png">

<img width="178" alt="Configuração Ofertas" src="https://user-images.githubusercontent.com/82406248/199001258-00694d19-1012-4601-9bcd-ffeacd75a437.png">
</p>

**Comment by BeatrizLdS** [comment]
Concluí
